### ISSUE TITLE
Make hat build on stable

### ISSUE THREAD

**Issue by Idolf** [google/hat-backup#18]
Remaining issues:

- [x] Make the diesel schemas run on stable. (Fixed in #15)
- [x] Stop depending on the FnBox from stable. (Fixed in #12)
- [x] Stop depend on unstable features from the test crate. (Fixed in #20).
- [x] Make Travis test stable as well.

**Comment by Idolf** [comment]
Our current benchmarks only works on nightly, but otherwise everything compiles on stable. To achieve this, we put the benchmarks under a feature gate. A separate issue (#23) has been filed to try and fix that problem as well.

**Comment by Idolf** [comment]
Fixed in #26.
